"""add notification_preferences

Revision ID: 3404e6b4acfe
Revises: b8f326057d6d
Create Date: 2026-09-01 21:59:25.577785

"""
from alembic import op
import sqlalchemy as sa


revision = '3404e6b4acfe'
down_revision = 'b8f326057d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('username', 'category')
    )
    op.drop_index(op.f('idx_push_subscriptions_username'), table_name='push_subscriptions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_push_subscriptions_username'), 'push_subscriptions', ['username'], unique=False)
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
