"""add push_subscriptions table

Revision ID: b8f326057d6d
Revises: 0001
Create Date: 2026-09-01 20:26:26.866492

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "b8f326057d6d"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "push_subscriptions",
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("p256dh", sa.Text(), nullable=False),
        sa.Column("auth", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("endpoint"),
    )
    op.create_index(
        op.f("ix_push_subscriptions_username"),
        "push_subscriptions",
        ["username"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_push_subscriptions_username"), table_name="push_subscriptions"
    )
    op.drop_table("push_subscriptions")
    # ### end Alembic commands ###
